# Generated by Django 5.0.6 on 2024-06-11 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("MonitoringApp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SensorData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sensor_name", models.CharField(max_length=255)),
                ("ecg_data", models.TextField()),
                ("spo2_level", models.FloatField()),
                ("heart_rate", models.IntegerField()),
                ("fall_detected", models.BooleanField(default=False)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
